#6 create sequence diagram for create email case
orion-services/talk pull request #11
Opened 2021-07-31 19:22 UTC by evandroLutz

2021-07-31 22:32 UTC, nikolasFreitas commented
### First of all, very good the diagram!

- I think you could put the position 6  out of the "flag email able to send" alternative, but inside of "email  not found". Because the response of User with "email not found' is for both alternatives of "flag email able..."
- Consider change "flag email able to send" for something with more meaningful. Maybe something like "ignore e-mail with errors" and "send to all strictly"

2021-08-01 02:10 UTC, evandroLutz commented
adjustments made.

-move emails not found case to email not found context and change flag name

2021-08-02 04:20 UTC, nikolasFreitas requested changes

2021-08-02 04:20 UTC, nikolasFreitas commented on docs/create-email.wsd
> +    alt ignore e-mail with errors
I think you could exchange this alt with the else of it ("send to all strictly") and remove the else.

2021-08-08 21:37 UTC, nikolasFreitas requested changes

2021-08-08 21:37 UTC, nikolasFreitas commented on docs/create-email.wsd
> +      Communication <-- client : send email successful
I think this is inverted. 
But I think this is not necessary because of the 15º step. And if template is successful, just let the flow continues, doesn't need the [template successful alternative].

2021-08-08 21:37 UTC, nikolasFreitas commented on docs/create-email.wsd
> +      DB --> Communication : template
Here you are saying that the template always exists, but this is not true. So I think you could have two alternatives inside "use template": 
1. Template found;
2. template NOT found;

Inside "template found" you should insert the step 10 (process template) and create one alternative or group: 'Template Error", but even with success, you don't have to return the send email successful because you are returning at the end of [Use template].

2021-08-08 21:37 UTC, nikolasFreitas commented on docs/create-email.wsd
> +  alt Use Template
In this diagram, it's saying that you can use templates only if in [e-mail not found] alternative. So, if the Communication service find the e-mails the template is never executed.

2021-08-08 21:37 UTC, nikolasFreitas commented on docs/create-email.wsd
> +  else Email Not Found
I think the diagram needs an extra alternative of "All e-mails not found" and this alternative (Email not found) could be renamed to "Some e-mails not found" or something like this.

2021-08-08 21:41 UTC, nikolasFreitas requested changes

2021-08-08 21:41 UTC, nikolasFreitas commented on docs/create-email.wsd
> +alt Authorized
I've generated the UML and this alternative doesn't shows up.

2021-08-08 21:41 UTC, nikolasFreitas commented on docs/create-email.wsd
> +title "Email service case"
The title is not compatible with the name of issue

2021-08-09 00:11 UTC, evandroLutz commented on docs/create-email.wsd
> +title "Email service case"
title changed.

2021-08-09 00:12 UTC, evandroLutz commented on docs/create-email.wsd
> +alt Authorized
althorized alt fixed

2021-08-10 01:54 UTC, merged